project:
  type: website

website:
  title: "spotify dashboard"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: about
      - href: dashboard.qmd
        text: Dahsboard
format:
  html:
    theme: [cosmo, custom.scss]
    toc: true



